spring.application.name=billcalculator

logging.level.org.springframework.security=DEBUG

currency.api.url=https://open.er-api.com/v6/latest/{base_currency}?apikey={apiKey}
currency.api.key=9cae2b33bd6a3ee056b453e7
